[package]
name = "elysium"
description = "Elysium Engine application"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[[bin]]
name = "elysium"
path = "src/main.rs"

[dependencies]
elysium-core.workspace = true
gpui.workspace = true
elysium-render.workspace = true
elysium-physics.workspace = true
# elysium-flux.workspace = true
elysium-asset.workspace = true
# elysium-ui.workspace = true
# elysium-editor.workspace = true
# elysium-net.workspace = true
# elysium-ml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
bytemuck.workspace = true
parking_lot.workspace = true
smallvec.workspace = true
wgpu.workspace = true
winit.workspace = true
pollster.workspace = true
fontdue.workspace = true
glam = { version = "0.28", features = ["serde"] }
image.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
