[package]
name = "elysium-asset"
description = "Elysium asset pipeline (Mimari §6.1)"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
elysium-core.workspace = true
elysium-render.workspace = true
tracing.workspace = true
tokio.workspace = true
serde = { version = "1.0", features = ["derive"] }
bincode.workspace = true
rkyv.workspace = true
image.workspace = true
num_cpus.workspace = true
md-5 = "0.10"
lz4 = "1.24"
zstd = "0.13"
